# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-12 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="KeyEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_code", models.CharField(max_length=10)),
                ("delay_time", models.IntegerField(default=0)),
                ("is_press", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MouseEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_pos", models.IntegerField()),
                ("y_pos", models.IntegerField()),
                ("delay_time", models.IntegerField(default=0)),
                ("is_press", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("key_code", models.CharField(max_length=10)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="macros.Profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mouseevent",
            name="recording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="macros.Recording"
            ),
        ),
        migrations.AddField(
            model_name="keyevent",
            name="recording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="macros.Recording"
            ),
        ),
    ]
