# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-19 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("macros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_key", models.CharField(max_length=10)),
                ("play_mode_key", models.CharField(max_length=10)),
                (
                    "current_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="macros.Profile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        )
    ]
