# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyevent',
            name='is_press',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mouseevent',
            name='is_press',
            field=models.BooleanField(default=True),
        ),
    ]
