# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("macros", "0002_auto_20200324_1454")]

    operations = [
        migrations.AlterField(
            model_name="mouseevent", name="x_pos", field=models.IntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="mouseevent", name="y_pos", field=models.IntegerField(default=0)
        ),
    ]
