# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_auto_20200324_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='auth_token',
            field=models.CharField(default='0300231504359234', max_length=150),
            preserve_default=False,
        ),
    ]
