# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0004_settings_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='auth_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
