# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("macros", "0004_auto_20200319_1820")]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="play_mode_status",
            field=models.BooleanField(default=False),
        )
    ]
