# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-25 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0005_auto_20200324_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='updates_needed',
            field=models.BooleanField(default=False),
        ),
    ]
