# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("macros", "0005_settings_play_mode_status")]

    operations = [
        migrations.RenameField(
            model_name="settings", old_name="play_mode_status", new_name="play_mode"
        )
    ]
