# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0007_settings_updates_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_recording',
            field=models.BooleanField(default=False),
        ),
    ]
