# Generated by Django 3.0 on 2020-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("macros", "0007_mouseevent_order_in_recording")]

    operations = [
        migrations.AddField(
            model_name="keyevent",
            name="order_in_recording",
            field=models.IntegerField(default=1),
            preserve_default=False,
        )
    ]
