# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-22 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("macros", "0008_settings_is_recording")]

    operations = [migrations.RemoveField(model_name="settings", name="updates_waiting")]
