# Generated by Django 3.0 on 2020-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("macros", "0010_profile_color")]

    operations = [
        migrations.RemoveField(model_name="profile", name="color"),
        migrations.AddField(
            model_name="profile",
            name="color_code",
            field=models.CharField(default="000000", max_length=6),
            preserve_default=False,
        ),
    ]
