# Generated by Django 3.0 on 2020-03-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("macros", "0012_auto_20200330_1250")]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="key_code",
            field=models.CharField(
                default=django.db.models.deletion.SET_NULL, max_length=10, null=True
            ),
        )
    ]
