# Generated by Django 3.0 on 2020-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0013_auto_20200331_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
