# Generated by Django 3.0 on 2020-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("macros", "0014_recording_is_temp")]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="key_code",
            field=models.CharField(max_length=10, null=True),
        )
    ]
