# Generated by Django 3.0 on 2020-04-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("macros", "0015_auto_20200331_1725")]

    operations = [migrations.RemoveField(model_name="settings", name="updates_needed")]
