# Generated by Django 3.0 on 2020-04-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0016_remove_settings_updates_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.CharField(default='fas fa-user', max_length=20),
        ),
    ]
