# Generated by Django 3.0 on 2020-04-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0017_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(default='fas fa-user', max_length=30),
        ),
    ]
