# Generated by Django 3.0 on 2020-04-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0019_settings_offer_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='show_social_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
