# Generated by Django 3.0 on 2020-04-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0022_auto_20200413_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(max_length=30),
        ),
    ]
