# Generated by Django 3.0 on 2020-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0023_auto_20200414_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
