# Generated by Django 3.0 on 2020-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0024_auto_20200414_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.CharField(default='fas fa-user', max_length=30),
        ),
    ]
