# Generated by Django 3.0 on 2020-04-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0025_auto_20200414_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='auth_token',
        ),
    ]
