# Generated by Django 3.0 on 2020-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0026_remove_settings_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyevent',
            name='key_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recording',
            name='key_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='play_mode_key',
            field=models.CharField(default='p', max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='quick_play_key',
            field=models.CharField(default='a', max_length=30),
        ),
        migrations.AlterField(
            model_name='settings',
            name='recording_key',
            field=models.CharField(default='r', max_length=30),
        ),
    ]
